import "@rainbow-me/rainbowkit/styles.css";
import type { AppProps } from "next/app";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { WagmiProvider } from "wagmi";
import { lightTheme, RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { config } from "../wagmi";
import "../styles/globals.css";
import TopBanner from "../components/TopBanner";
import Head from "next/head";
import Footer from "../components/Footer";
import { ThemeProvider } from "@emotion/react";
import { myButtonTheme } from '../components/StyledButton';
import { grey } from '@mui/material/colors';

// required by rainbowkit
const client = new QueryClient();

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <WagmiProvider config={config}>
      <QueryClientProvider client={client}>
        <RainbowKitProvider theme={lightTheme({
          accentColor: grey[700],
        })}>
          <Head>
            <title>Cookrypt App</title>
            <meta
              content="Generated by @rainbow-me/create-rainbowkit"
              name="description"
            />
            <link href="/favicon.ico" rel="icon" />
          </Head>
          <ThemeProvider theme={myButtonTheme}>
            <div
              style={{
                height: "100vh",
                display: "flex",
                flexDirection: "column",
              }}
            >
              <TopBanner />
              <Component {...pageProps} />
              <Footer />
            </div>
          </ThemeProvider>
        </RainbowKitProvider>
      </QueryClientProvider>
    </WagmiProvider>
  );
}

export default MyApp;
